In [2]:
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
#加载数据集
digits = datasets.load_digits()
X=digits.data
y=digits.target
#划分数据集
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)
(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

((1347, 64), (450, 64), (1347,), (450,))

In [4]:
param_grid =[
    {
        'weights':['uniform'],
        'n_neighbors': [i for i in range(1,11)]
    },
    {
        'weights':['distance'],
        'n_neighbors': [i for i in range(1,11)],
        'p': [i for i in range(1,6)]
    }
]

In [5]:
#交叉验证
#网格搜索
from sklearn.model_selection import GridSearchCV

In [8]:
knn_clf = KNeighborsClassifier()
#GridSearchCV?
#得到最好的参数
gridSearchCV = GridSearchCV(estimator=knn_clf, param_grid=param_grid)

In [9]:
%%time
gridSearchCV.fit(X_train, y_train)

CPU times: user 46.5 s, sys: 339 ms, total: 46.8 s
Wall time: 47.7 s


GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid=[{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                          'weights': ['uniform']},
                         {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                          'p': [1, 2, 3, 4, 5], 'weights': ['distance']}])

In [10]:
gridSearchCV.best_estimator_

KNeighborsClassifier(n_neighbors=9, p=3, weights='distance')

In [12]:
gridSearchCV.best_params_

{'n_neighbors': 9, 'p': 3, 'weights': 'distance'}

In [ ]:
#数据归一化
#one-hot encoding
#batch normalization 
#normalization:转化成0-1之间的比例
#standardization: 转化成mean=0, s=1

In [13]:
x = np.random.randint(0,100,100)
x

array([55, 17, 10, 59, 48, 43, 61, 78, 80,  2, 40, 16, 78, 42, 26, 46, 49,
       50, 87, 45, 52, 71, 43, 19, 43, 62, 99, 36, 25, 26, 18, 37,  0, 95,
       34, 19, 91, 18,  0, 56, 59, 56, 97, 16, 88, 75, 42, 12, 48, 23, 18,
       78, 30, 40, 49,  3, 21, 11, 15, 66, 49, 98, 41, 92, 32, 55, 84,  3,
       51, 54,  9, 26,  9, 31, 89, 46, 60, 66, 66, 29, 63, 57, 11, 42, 43,
       19, 17, 99, 86, 11, 11, 99, 12, 44, 71, 95, 29, 62, 10,  7])

In [14]:
#normalization
norm = [(x-np.min(x))/(np.max(x)-np.min(x))]
norm

[array([0.55555556, 0.17171717, 0.1010101 , 0.5959596 , 0.48484848,
        0.43434343, 0.61616162, 0.78787879, 0.80808081, 0.02020202,
        0.4040404 , 0.16161616, 0.78787879, 0.42424242, 0.26262626,
        0.46464646, 0.49494949, 0.50505051, 0.87878788, 0.45454545,
        0.52525253, 0.71717172, 0.43434343, 0.19191919, 0.43434343,
        0.62626263, 1.        , 0.36363636, 0.25252525, 0.26262626,
        0.18181818, 0.37373737, 0.        , 0.95959596, 0.34343434,
        0.19191919, 0.91919192, 0.18181818, 0.        , 0.56565657,
        0.5959596 , 0.56565657, 0.97979798, 0.16161616, 0.88888889,
        0.75757576, 0.42424242, 0.12121212, 0.48484848, 0.23232323,
        0.18181818, 0.78787879, 0.3030303 , 0.4040404 , 0.49494949,
        0.03030303, 0.21212121, 0.11111111, 0.15151515, 0.66666667,
        0.49494949, 0.98989899, 0.41414141, 0.92929293, 0.32323232,
        0.55555556, 0.84848485, 0.03030303, 0.51515152, 0.54545455,
        0.09090909, 0.26262626, 0.09090909, 0.31

In [29]:
X = np.random.randint(0,100,(50,2)) #50X2
X[:,0]

array([89, 93, 40, 23,  3, 18, 16, 57, 52,  5,  0, 14, 99, 12, 79, 90, 16,
       50, 27, 24, 72, 46, 14, 79, 29, 23, 11, 57, 14, 99, 40, 95, 22, 51,
       33, 76, 70, 19, 24, 77, 91, 25, 89, 10, 81, 69, 48, 60, 72, 17])

In [30]:
X = np.array(X, dtype=np.float64) #调整数据的类型int/float

In [34]:
X[:,0] = (X[:,0]-np.min(X[:,0]))/(np.max(X[:,0])-np.min(X[:,0]))
X[:,1] = (X[:,1]-np.min(X[:,1]))/(np.max(X[:,1])-np.min(X[:,1]))

In [36]:
X

array([[0.8989899 , 0.37234043],
       [0.93939394, 0.92553191],
       [0.4040404 , 0.81914894],
       [0.23232323, 0.27659574],
       [0.03030303, 0.0212766 ],
       [0.18181818, 0.        ],
       [0.16161616, 0.68085106],
       [0.57575758, 0.06382979],
       [0.52525253, 0.18085106],
       [0.05050505, 0.23404255],
       [0.        , 0.87234043],
       [0.14141414, 0.42553191],
       [1.        , 0.55319149],
       [0.12121212, 0.17021277],
       [0.7979798 , 0.67021277],
       [0.90909091, 0.22340426],
       [0.16161616, 0.18085106],
       [0.50505051, 0.42553191],
       [0.27272727, 0.74468085],
       [0.24242424, 0.07446809],
       [0.72727273, 0.25531915],
       [0.46464646, 0.92553191],
       [0.14141414, 0.73404255],
       [0.7979798 , 0.37234043],
       [0.29292929, 1.        ],
       [0.23232323, 0.13829787],
       [0.11111111, 0.36170213],
       [0.57575758, 0.0106383 ],
       [0.14141414, 0.13829787],
       [1.        , 0.30851064],
       [0.

In [37]:
np.mean(X[:,0])

0.4686868686868687

In [38]:
np.std(X[:,0])

0.30837707232020733

In [46]:
#standardization
X2 = np.random.randint(0,100,(50,2)) #50X2
X2 = np.array(X2, dtype=np.float64) #调整数据的类型int/float
X2mean_col1 = np.mean(X2[:,0])
X2mean_col2 = np.mean(X2[:,1])
print(X2mean_col1)
print(X2mean_col2)

47.22
44.7


In [47]:
X2std_col1 = np.std(X2[:,0])
X2std_col2 = np.std(X2[:,1])
print(X2std_col1)
print(X2std_col2)

28.198787207963395
29.057357071832946


In [49]:
X2[:,0]=(X2[:,0]-X2mean_col1)/X2std_col1
X2[:,1]=(X2[:,1]-X2mean_col2)/X2std_col2

In [50]:
X2

array([[ 0.52413602,  0.4921301 ],
       [ 0.8787612 , -0.47148128],
       [-1.46176499,  0.45771541],
       [-1.39083996, -1.33184859],
       [-0.61066456, -1.50392205],
       [-0.39788945, -0.81562821],
       [-0.00780175, -1.33184859],
       [ 1.30431141,  0.76744764],
       [ 0.80783616,  0.52654479],
       [ 1.44616149,  1.76547371],
       [-0.82343967, -0.4026519 ],
       [-0.43335197, -1.12536044],
       [ 1.51708652,  1.49015617],
       [ 1.23338638, -0.54031067],
       [ 1.51708652,  1.3869121 ],
       [ 0.13404832,  0.32005664],
       [ 1.55254904,  1.04276517],
       [ 0.59506105,  1.42132679],
       [-1.49722751, -0.54031067],
       [-0.22057686, -0.02409028],
       [-0.61066456, -0.81562821],
       [ 1.69439911, -1.40067797],
       [ 0.16951084,  0.83627702],
       [ 0.13404832,  0.0447391 ],
       [ 1.44616149, -1.2630192 ],
       [ 0.55959853,  0.52654479],
       [ 0.16951084,  0.42330071],
       [ 1.33977393,  1.83430309],
       [-0.96528974,

In [51]:
# mean, std 
# 0 1
print(np.mean(X2[:,0]))
print(np.mean(X2[:,1]))
print(np.std(X2[:,0]))
print(np.std(X2[:,1]))

2.55351295663786e-17
-1.2656542480726783e-16
1.0
0.9999999999999999
