In [1]:
import numpy as np

In [2]:
#创建向量（ndarray）

In [4]:
v1 = np.array([1,2,3])
type(v1)

numpy.ndarray

In [7]:
v2 = np.arange(10)
type(v2)
v2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# 不用反复加载数据

In [9]:
# 属性一：数据类型

In [11]:
v2.dtype #int数字类型

dtype('int64')

In [12]:
v3 = np.array([1, 2, 3, 4.])
v3.dtype

dtype('float64')

In [14]:
v4 = np.array([1,2,3], dtype=np.float64)
v4.dtype

dtype('float64')

In [15]:
# 属性二：维度

In [16]:
v1.ndim

1

In [17]:
# 属性三：形状

In [18]:
v1.shape

(3,)

In [19]:
# 属性四：大小
v1.size

3

In [25]:
m = np.array([[1,2,3],[2,3,4]])
v5.dtype

dtype('int64')

In [26]:
m.ndim

2

In [27]:
m.shape

(2, 3)

In [29]:
m.size

6

In [31]:
m2 = np.arange(15).reshape((3,5))
m2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
m3 = np.arange(15).reshape((3,5,1))
m3

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

In [33]:
m3.shape

(3, 5, 1)

In [34]:
# 特殊数组的定义
# 注意相同

In [35]:
v1 = np.zeros(10)
v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
m2 = np.zeros_like(m)
m2

array([[0, 0, 0],
       [0, 0, 0]])

In [40]:
m4 = np.zeros(m.shape)
m4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
m3 = np.zeros((3,2))
m3

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [44]:
# 特殊的数列

In [46]:
# 等差数列

In [48]:
np.linspace(0,2*np.pi,num=10)

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [50]:
# 随机数

In [51]:
np.random.randint(10) #左闭右开

3

In [54]:
from random import randint
[randint(1,5) for i in range(100)] #左闭右闭

[2,
 4,
 1,
 5,
 3,
 2,
 5,
 2,
 5,
 3,
 5,
 5,
 3,
 5,
 2,
 5,
 1,
 5,
 4,
 5,
 3,
 4,
 1,
 5,
 4,
 3,
 4,
 2,
 4,
 2,
 5,
 2,
 3,
 2,
 4,
 2,
 1,
 4,
 4,
 5,
 1,
 2,
 3,
 4,
 4,
 5,
 1,
 4,
 4,
 3,
 4,
 5,
 1,
 4,
 2,
 1,
 1,
 5,
 2,
 4,
 3,
 4,
 1,
 3,
 4,
 1,
 4,
 3,
 3,
 5,
 2,
 4,
 3,
 5,
 2,
 2,
 2,
 3,
 2,
 3,
 4,
 1,
 5,
 5,
 4,
 5,
 4,
 3,
 4,
 3,
 5,
 3,
 2,
 4,
 3,
 2,
 5,
 4,
 4,
 1]

In [55]:
np.random.randint(20,101)

87

In [56]:
np.random.randint?

In [59]:
np.random.randint(20,101,(3,5)) # 直接生成随机数列表

array([[87, 88, 39, 44, 40],
       [52, 63, 37, 48, 49],
       [57, 40, 97, 79, 62]])

In [60]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [62]:
np.random.seed(666)
np.random.randint(20,101,(3,5))

array([[22, 65, 50, 82, 90],
       [93, 50, 56, 81, 71],
       [80, 48, 34, 83, 36]])

In [63]:
np.random.random((3,5))#小于1

array([[0.20024754, 0.74415417, 0.192892  , 0.70084475, 0.29322811],
       [0.77447945, 0.00510884, 0.11285765, 0.11095367, 0.24766823],
       [0.0232363 , 0.72732115, 0.34003494, 0.19750316, 0.90917959]])

In [64]:
np.random.normal()
# 生成随机样本

0.028016723832884196

In [65]:
np.random.normal(0,1,10)

array([ 0.40855719,  0.53928565, -1.54984701,  0.72946452, -0.32695477,
        1.14133677,  0.45243662, -2.23496877,  1.27047766, -0.72928821])

In [66]:
np.random.normal(0,1,(3,5))

array([[ 1.35925255, -1.20990266, -0.04618272, -0.44118244,  0.46953431],
       [ 0.44325817, -1.66738875, -1.81731749, -1.39753916,  0.78392691],
       [-0.29129965,  0.67049043,  0.706931  ,  1.42965241, -0.41407013]])

In [67]:
np.random.normal(0,5,(3,5))

array([[-6.63361371, -0.7440094 ,  1.73856443,  3.05153955, -5.87663013],
       [ 4.1492684 , -1.5118376 , -0.21635235,  0.33534824, -7.95514087],
       [ 0.08525562, -9.36482953, -4.82289518, -0.02101947,  2.37475237]])

In [68]:
# 切片和访问

In [69]:
matrix = np.arange(15).reshape((3,-1))
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
matrix[1][1]

6

In [71]:
matrix[1,1]

6

In [72]:
matrix[2,4]

14

In [74]:
vec=np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
vec[:2]

array([0, 1])

In [76]:
matrix[1:,3:]

array([[ 8,  9],
       [13, 14]])

In [77]:
# 乘法运算

In [79]:
m1 = np.array([[2,3,4],[1,3,4]]) #2*3
m2 = np.array([[2,3,4],[1,3,4]])

array([[2, 3, 4],
       [1, 3, 4]])

In [80]:
m1*m2

array([[0, 0, 0],
       [0, 0, 0]])

In [83]:
m3 = np.array([[2,3],[3,4],[1,2]]) # 3*2
m4 = m1.dot(m3)
m4

array([[17, 26],
       [15, 23]])