In [1]:
print('hello')

hello


In [2]:
#jupyter notebook：支持markdown，交互式，编辑器

In [3]:
import numpy as np
np.__version__

'1.21.5'

In [5]:
import tensorflow as tf
tf.__version__

'2.9.1'

In [8]:
m1 = [[1,2],[3,4]]
m2 = [[3,2],[4,4]]
m1+m2

[[1, 2], [3, 4], [3, 2], [4, 4]]

In [9]:
m1*m2

TypeError: can't multiply sequence by non-int of type 'list'

In [10]:
vec1 = np.array([i for i in range(5)])
vec1

array([0, 1, 2, 3, 4])

In [11]:
vec2 = np.array([i for i in range(5)])
vec2

array([0, 1, 2, 3, 4])

In [12]:
vec1+vec2

array([0, 2, 4, 6, 8])

In [13]:
# 支持矢量运算
# 速度快
# shift-enter 执行
# esc, m -> 切换至markdown
# esc, y -> 切换至代码

In [15]:
# 魔法命令
v = [i for i in range(1000000)]
%timeit res = [i**2 for i in v]

342 ms ± 7.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
nv = np.array([i for i in range(1000000)])
%timeit res2 = nv**2
# 运行多次取平均值

928 µs ± 27.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [18]:
# 为什么numpy快？-> 使用C语言编numpy的库